services:
  app:
    build: .
    container_name: django
    restart: always
    env_file:
      - django.env
    expose:
      - "8000"
    volumes:
      - .:/app
    command: ["sh", "/entrypoint.sh"]
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ngx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cows_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: