# Generated by Django 5.0.6 on 2024-05-26 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount_kg', models.IntegerField()),
                ('cron_schedule', models.CharField(max_length=100)),
                ('last_measured', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_milk', models.DateTimeField()),
                ('cron_schedule', models.CharField(max_length=100)),
                ('amount_l', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mass_kg', models.IntegerField()),
                ('last_measured', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('birthdate', models.DateTimeField()),
                ('condition', models.CharField(max_length=100)),
                ('has_calves', models.BooleanField()),
                ('feeding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cows.feeding')),
                ('milk_production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cows.milkproduction')),
                ('weight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cows.weight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
