# Generated by Django 5.0.6 on 2024-05-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
