services:
  web:
    image: cows_project:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "/entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cows_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: