services:
  app:
    build: .
    container_name: django
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
#    command: python manage.py runserver 0.0.0.0:8000
    command: ["sh", "/entrypoint.sh"]
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cows_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: